### ISSUE TITLE
Connect with Postgres

### ISSUE THREAD

**Issue by Harryman** [Harryman/hashd#2]
We need a backing database to store validated messages and content. 

Matrix and Gogs which are target early applications also support Postgres as a backing database. If there are any good reasons not to or better alternatives voice your opinions here.

**Comment by cryptoquick** [comment]
There are plenty of reasons why this is a good choice. The only downside I can think of is that it's not as portable as an embedded database, like I used in the Rust version, but with Docker, that's no longer an issue. So, that sounds good to me.
